### ISSUE TITLE
Mongo Exit Code 1

### ISSUE THREAD

**Issue by Onemanwolf** [DanWahlin/CodeWithDanDockerServices#21]
Starting mongo ... 
Starting mongo ... done
Recreating node-codewithdan ... done
nginx is up-to-date
Attaching to redis, mongo, node-codewithdan, nginx
mongo    | standard_init_linux.go:211: exec user process caused "no such file or directory"
mongo exited with code 1

Connection error:  MongoNetworkError: failed to connect to server [mongo:27017] on first connect [Error: getaddrinfo ENOTFOUND mongo
node-codewithdan | 22:26:39 0|codewithdan  |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26) {
node-codewithdan | 22:26:39 0|codewithdan  |   name: 'MongoNetworkError',
node-codewithdan | 22:26:39 0|codewithdan  |   [Symbol(mongoErrorContextSymbol)]: {}
node-codewithdan | 22:26:39 0|codewithdan  | }]

**Comment by DanWahlin** [comment]
Guessing you're on Windows?

I just ran it on Mac and things work properly but something definitely changed for Mongo when running this on Windows as I'm seeing the same error. I'll dig into it when I get some free time. I suspect it's volume or directory security related but hard to say.

**Comment by DanWahlin** [comment]
I'm running WSL (WSL2 actually) on Windows 10 with Docker and it turns out you have to clone the repo using a WSL (Linux) command prompt rather than a Windows command prompt. From there Node has to be installed into WSL if it's not already and then you can run through the instructions in the readme. Worked great once I cloned it using the Linux shell. 

Readme has been updated to mention these changes. I'm hoping that's the issue you're hitting as well.

**Comment by Onemanwolf** [comment]
Dan

Awesome! Thank you, love your work!  I know you're very busy so thanks for
looking into it and I learned a lot more by facing this issue, so a good
side effect.  I am watching all your courses on Kubernetes big help again
thank you for all your hard work.

VR
Tim

**Comment by DanWahlin** [comment]
Happy to help - thanks. I didn't want to close this out until I knew you had it working (it sounds like you have it working but I wanted to double-check). Thanks for letting me know about the issue.

**Comment by DanWahlin** [comment]
Going to close this out since I'm guessing you're all set. Feel free to re-open if there's still a problem.
