### ISSUE TITLE
host not found in upstream "node1:8080" in /etc/nginx/nginx.conf:9

### ISSUE THREAD

**Issue by tbudhe** [DanWahlin/CodeWithDanDockerServices#3]
Hello Sir,
Thanks for plurasight tutorial. It help me a lot. 

I am getting above exception on docker-compose up. I did share you a git hub link to access my code.

It's very simple code. I would really appreciate your help.

https://github.com/tusharbudhe0302/dockernode

**Comment by DanWahlin** [comment]
Glad you enjoyed the course...thanks. Are you getting this error with my project (this one) or with the project you link to? It's not clear from your message.

That error occurs when the upstream (Node server/container in my project) isn't starting successfully, has a wrong port defined, or some other error. But, let me know which project you're referring to.

**Comment by tbudhe** [comment]
Thanks @DanWahlin , There was issue in my configuration which I a, able to fixed latter. Thanks for your plurasight tutorial. It help me a lot.
