### ISSUE TITLE
Question: Which Commit

### ISSUE THREAD

**Issue by preflight** [DanWahlin/CodeWithDanDockerServices#4]
@DanWahlin - Can you tell me which [commit](https://github.com/DanWahlin/CodeWithDanDockerServices/commits/master) would be best to checkout for following along with the Pluralsight [course](https://app.pluralsight.com/library/courses/docker-web-development/table-of-contents)? I'm on Module 8 (Managing Containers with Docker Compose) and would like to take a look at the code prior to the Kubernetes updates and other things not yet covered in the lessons. Thanks - enjoying the course.

**Comment by DanWahlin** [comment]
Hi there. I don't know the specific commit that would have that. That's not something I track for these types of projects. You can run the project as shown in the class without Kubernetes. The readme has the required steps if you're interested (you can ignore the Kubernetes section).
